spring.application.name=hospital-management-backend
server.port=8080

spring.datasource.url=${postgresql://hospital_db_i8zr_user:5kcmVa7ZBKLZeBtIx1Aw4I7rzmV7qyDf@dpg-d6kl4mn5r7bs73e2vi50-a.oregon-postgres.render.com/hospital_db_i8zr}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

hms.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY
hms.jwt.expiration=86400000
